name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  specs:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby-version: ['2.7', '3.0', '3.1', 'head']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: phlex/setup
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./phlex
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: phlex/tests
        run: bundle exec sus
        working-directory: ./phlex

      - name: phlex/type-check
        run: bundle exec solargraph typecheck --level typed
        working-directory: ./phlex

      - name: phlex/rubocop
        run: bundle exec rubocop
        working-directory: ./phlex


      - name: phlex-rails/setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: ./phlex-rails

      - name: phlex-rails/tests
        run: bundle exec sus
        working-directory: ./phlex-rails

  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./docs
          ruby-version: "3.2"
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Build docs
        run: bundle exec ./build.rb
